import { CategoryType } from './types'

const productCategories: CategoryType[] = [
  { id: 1, name: 'Analgesics' },
  { id: 2, name: 'Antacids' },
  { id: 3, name: 'Anti-Allergy' },
  { id: 4, name: 'Anti-Biotics' },
  { id: 5, name: 'Anti-Depressants' },
  { id: 6, name: 'Anti-Diabetics' },
  { id: 7, name: 'Anti-Duretics' },
  { id: 8, name: 'Anti-Epileptics' },
  { id: 9, name: 'Anti-Fungal' },
  { id: 10, name: 'Anti-Histamines' },
  { id: 11, name: 'Anti-Hypertensive' },
  { id: 12, name: 'Anti-Malaria' },
  { id: 13, name: 'Anti-Oxidants' },
  { id: 14, name: 'Anti-Psychotics' },
  { id: 15, name: 'Anti-Reflux' },
  { id: 16, name: 'Anti-Retovirals/Anti-Virals' },
  { id: 17, name: 'Anti-Ulcers' },
  { id: 18, name: 'Appetite Stimulant' },
  { id: 19, name: 'Beauty products' },
  { id: 20, name: 'Blood tonics/ Capsules' },
  { id: 21, name: 'Cardiovascular drugs' },
  { id: 22, name: 'Central Nervous System (CVS) Drugs' },
  { id: 23, name: 'Contraceptives' },
  { id: 24, name: 'Cough and Cold Drugs' },
  { id: 25, name: 'Dermatological Drugs' },
  { id: 26, name: 'Eye/Ear/Nose Drugs' },
  { id: 27, name: 'Feminine Hygine' },
  { id: 28, name: 'Heamatinic' },
  { id: 29, name: 'Immuno Stimulants' },
  { id: 30, name: 'Immuno Suppressants' },
  { id: 31, name: 'Infusion' },
  { id: 32, name: 'Injection Im/Iv' },
  { id: 33, name: 'Insulins' },
  { id: 34, name: 'Iron Supplements' },
  { id: 35, name: 'Joint and Bone support Drugs' },
  { id: 36, name: 'Laxatives' },
  { id: 37, name: 'Lipid lowering Drugs' },
  { id: 38, name: 'Liver Supplements and Drugs' },
  { id: 39, name: 'Lozenges' },
  { id: 40, name: 'Lubricants' },
  { id: 41, name: 'Medical and Hospital Equipments' },
  { id: 42, name: 'Oncology Drugs' },
  { id: 43, name: 'Oral and Dental care' },
  { id: 44, name: 'Oral Rehydration' },
  { id: 45, name: 'Probiotic' },
  { id: 46, name: 'Respiratory Drugs' },
  { id: 47, name: 'Sedatives' },
  { id: 48, name: 'Sexual wellness and Fertility Drugs' },
  { id: 49, name: 'Sleep aid' },
  { id: 50, name: 'Vaccines' },
  { id: 51, name: 'Warm Drugs/Expeller' },
  { id: 52, name: 'Weight loss' },
  { id: 53, name: 'Wellness' },
  { id: 54, name: 'Wound dressing' },
]

export default productCategories
